Д.з. 4.11 и 5.12
darkbearru/ps-bnb pull request #1
Opened 2024-12-17 15:19 UTC by darkbearru

2024-12-23 19:18 UTC, alex13slem requested changes

2024-12-23 19:18 UTC, alex13slem commented on src/room/room.controller.ts
> +    async update(@Param('id') id: string, @Body() dto: RoomDto) {
На создание и на обновление должны быть разные DTO. Например при обновлении вы не можете поменять id.

2024-12-23 19:18 UTC, alex13slem commented on src/room/room.service.ts
> +            .catch( () => { return null; });
Зачем гасить ошибку?

2024-12-23 19:18 UTC, alex13slem commented on src/schedule/schedule.controller.ts
> +        dto.status = ScheduleStatus.Pending;
Имеет ли смысл передавать статус в dto, если потом его изменять в любом случае? Относитесь к dto как иммутабельному объекту.

2024-12-23 19:18 UTC, alex13slem commented on src/schedule/schedule.controller.ts
> +        dto.status = ScheduleStatus.Pending;
И изменение статуса - логика не контроллера, а сервиса.

2024-12-24 04:40 UTC, darkbearru commented on src/room/room.service.ts
> +            .catch( () => { return null; });
Когда писал, на ошибки срабатывал глобальный Exception, соответственно не получалось вернуть свою ошибку.
Сейчас всё проверил, нормально и без catch работает, наверное когда начинал писать nest не в режиме watch был запущен, сейчас всё поправлю

2024-12-24 04:43 UTC, darkbearru commented on src/schedule/schedule.controller.ts
> +        dto.status = ScheduleStatus.Pending;
Понял, исправляю

2024-12-24 15:58 UTC, darkbearru commented on src/room/room.service.ts
> +            .catch( () => { return null; });
Всё, разобрался для какого случая я так сделал, меняешь уже созданный id, удалением одной цифры, ожидая получить что ничего не найдено, получаешь такую ошибку «Cast to ObjectId failed for value "676ad6a5889403dc21e84d9" (type string) at path "_id" for model "RoomModel"» в консоле, а в ответе 500-ю, а если внутри id цифру меняешь не изменяя длины тогда всё норм 404 получаешь.  
Я пока убрал, а как лучше подобные ошибки обрабатывать? Через catch и делать throw из сервиса работы с базой?

2024-12-24 15:59 UTC, darkbearru commented on src/schedule/schedule.controller.ts
> +        dto.status = ScheduleStatus.Pending;
Исправлено

2025-01-03 06:23 UTC, alex13slem requested changes

2025-01-03 06:23 UTC, alex13slem commented on src/room/room.controller.ts
> +        return this.roomService.getAll();
Все методы сервиса - это промисы и стоит оборачивать их вызов в try/catch и дожидаться их выполнения с помощью await. Тем более если у Вас нет глобального обработчика ошибок.

2025-01-03 06:23 UTC, alex13slem commented on src/room/room.controller.ts
> +            throw new HttpException(ROOM_NOT_FOUND, HttpStatus.NOT_FOUND);
Есть сокращения, утилитарные классы по типу NotFoundExeption

2025-01-14 17:10 UTC, merged